# Generated by Django 5.1 on 2024-09-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_grade_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
