# Generated by Django 5.1 on 2024-09-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_subject',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_surname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
