# Generated by Django 5.1 on 2024-09-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_teacher_teacher_subject_teacher_teacher_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_year',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
