# Generated by Django 5.1 on 2024-09-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_class_class_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_surname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
