# Generated by Django 5.1 on 2024-09-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_student_student_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule_name',
            new_name='schedule_class',
        ),
        migrations.AddField(
            model_name='grade',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
